### ISSUE TITLE
서버 에러 로그 (EfeGear)

### ISSUE THREAD

**Issue by fpwltmxlf** [apexnetwork/SwiftBukkit-Issues#3]
[WARNING] [EfeGear] Task #848128 for EfeGear v1.8 for 1.5 generated an exception
java.lang.NullPointerException
	at me.efe.efegear.EfeListener$TimeTask.run(EfeListener.java:91)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:67)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
	at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:516)
	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:280)
	at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:480)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:412)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

라고 일정 시간마다 계속 뜨네요.. 기존 Spigot 에서는 안이랬던것 같습니다

**Comment by swan201** [comment]
EfeGear 서버 문제로인한 버그로 알고 있습니다.

**Comment by EntryPointKR** [comment]
EfeGear 플러그인은 오픈소스가 아니므로 무엇이 문제인지 알 수 없습니다.
EfeGear 플러그인의 클래스에서 예외가 발생해 버킷 문제가 아닐 확률이 큽니다
